[app]
    listen_http = ":80"
    listen_https = ":443"
    request_timeout = "8s"
    shutdown_timeout = "10s"

[log]
    level = "info"
    size = "256m"
    dir = "logs"

[database]
    [database.mysql]
	debug = true
	log = "mysql.log"
        link = "voidengine:123456@tcp(127.0.0.1:3306)/voidengine?charset=utf8mb4&parseTime=true&loc=Local&timeout=10s"
    [database.clickhouse]
	debug = true
	log = "clickhouse.log"
        link = "tcp://127.0.0.1:9001/voidengine?username=default&password=123456&read_timeout=10s"
